.TH sciteproj 1 "9 January 2014" "Version 0.7.96"
.SH NAME
SciteProj - a Project Manager for the SciTE editor
.SH DESCRIPTION
.B SciteProj
is a Project Manager for the SciTE editor - It is used to group a bunch 
of files into a project for easy access in SciTE giving the possibility 
to group files in folders, and saves the project to disc in XML format. 
It is based on the program ScitePM by Roy Wood. It uses the director 
interface of SciTE to communicate between SciTE and SciteProj.
.SH OPTIONS
.IP "-s, --scite FILENAME"
Sets the filename for the instance of SciTE to open.
.IP "-v, --version"
Displays the version number of SciteProj
.IP "-h, --help"
Display a short help
.SH CONFIG FILE
The config file that SciteProj is using is named sciteprojrc.lua, and is loaded
from the directory where sciteproj is started in. - If this file isn't found, 
sciteproj searches for the file in the users $HOME/.config/ directory. It is 
loaded on every program start. There is a menuitem in the program to open the 
file directly in SciTE for editing. 
If there isn't a .sciteproj in the user home when starting SciteProj, 
one will be created filled with default values.
The following options are supported in the config file:
.IP "xpos, ypos, xsize and ysize"
Specifies the position and size of the program window on start
.IP "give_scite_focus"
.SH AUTHOR
.B SciteProj 
was written by Andreas Rönnquist <gusnan@gusnan.se>.
